name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Image Version
      run: echo "IMAGE_VERSION=${GITHUB_SHA:0:7}" >> $GITHUB_ENV
    - name: Build Docker Image
      run: docker build -t ghcr.io/spoenemann/static-message:$IMAGE_VERSION .
    - name: Push Docker Image
      run: |
        echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        docker push ghcr.io/spoenemann/static-message:$IMAGE_VERSION
      if: github.repository == 'spoenemann/docker-static-message' && github.ref == 'refs/heads/master'
